# Generated by Django 3.0.8 on 2021-01-05 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='作成時間')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新時間')),
                ('is_delete', models.BooleanField(default=False, verbose_name='削除タグ')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ユーザーID')),
                ('nickname', models.CharField(blank=True, max_length=13, null=True, verbose_name='昵称')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='メールアドレス')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='年齢')),
                ('gender', models.CharField(blank=True, choices=[(1, '男'), (2, '女'), (3, '秘密')], max_length=2, null=True, verbose_name='性別')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='Store/user_picture', verbose_name='用户头像')),
                ('is_active', models.BooleanField(default=False, verbose_name='激活状态')),
            ],
            options={
                'verbose_name': 'ユーザー情報',
                'verbose_name_plural': 'ユーザー情報',
                'db_table': 'my_user_info',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='作成時間')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新時間')),
                ('is_delete', models.BooleanField(default=False, verbose_name='削除タグ')),
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='認証ID')),
                ('identity_type', models.SmallIntegerField(blank=True, choices=[(1, 'ユーザー名とパスワード認証'), (2, 'メールとパスワード認証'), (3, '指紋認証')], default=1, verbose_name='認証タイプ')),
                ('identifier', models.CharField(max_length=255, unique=True, verbose_name='識別子')),
                ('is_active', models.BooleanField(default=False, verbose_name='激活状态')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user', models.ForeignKey(max_length=50, on_delete=django.db.models.deletion.CASCADE, to='user.UserInfo', verbose_name='ユーザー')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '認証',
                'verbose_name_plural': '認証',
                'db_table': 'my_auths',
            },
        ),
    ]
