# Generated by Django 3.0.8 on 2020-08-30 12:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementResults',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='作成時間')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新時間')),
                ('is_delete', models.BooleanField(default=False, verbose_name='削除タグ')),
                ('data_id', models.CharField(max_length=128, primary_key=True, serialize=False, verbose_name='データ番号')),
                ('heartbeat', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='心拍数')),
                ('pulse', models.DecimalField(decimal_places=1, max_digits=4, verbose_name='脈拍数')),
                ('level', models.IntegerField(default=0, verbose_name='健康レベル')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': '測定結果',
                'verbose_name_plural': '測定結果',
                'db_table': 'df_measurement_results',
            },
        ),
    ]
