# Generated by Django 3.0.8 on 2020-08-30 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_measurementresults'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measurementresults',
            name='data_id',
            field=models.AutoField(max_length=128, primary_key=True, serialize=False, verbose_name='データ番号'),
        ),
    ]
