# Generated by Django 3.0.8 on 2020-08-31 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20200830_2345'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurementresults',
            name='heartbeat',
        ),
    ]
