# Generated by Django 3.0.8 on 2020-12-22 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeasurementResults',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='作成時間')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='更新時間')),
                ('is_delete', models.BooleanField(default=False, verbose_name='削除タグ')),
                ('record_id', models.AutoField(primary_key=True, serialize=False, verbose_name='データ番号')),
                ('level', models.IntegerField(default=0, verbose_name='健康レベル')),
                ('pulse', models.DecimalField(decimal_places=1, max_digits=3, verbose_name='脈拍数')),
            ],
            options={
                'verbose_name': '測定結果',
                'verbose_name_plural': '測定結果',
                'db_table': 'records',
            },
        ),
    ]
